### ISSUE TITLE
multiprocessing fails on windows

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#36]
When using chimera on Windows, we get the error message below. It seems an common error with multiprocessing on Windows and seems to be fixed on Python3. http://bugs.python.org/issue17314

Error message:

```
Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\multiprocessing\forking.py", line 380, in main
 prepare(preparation_data)
 File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\multiprocessing\forking.py", line 489, in prepare
 file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named chimera
```

**Comment by phsilva** [comment]
Hum... I don't see chimera on your traceback messages. Why is this a Chimera problem? We installed and used Chimera on Windows with no such issues.

**Comment by tribeiro** [comment]
This is some issue with how windows are loading python. Just renaming the script with ".py" extension (as suggested here https://github.com/gtaylor/EVE-Market-Data-Uploader/issues/7) fixes the problem. Maybe having setup.py install the scripts with ".py" on windows extension will provide a fix for this.

**Comment by phsilva** [comment]
Still don't make sense to me. Not sure if its related to scripts.

@wschoenell: how do you reproduce this issue?

**Comment by tribeiro** [comment]
Install Anaconda/Python on windows and, after installing chimera, run chimera and take an exposure with chimera-cam… 

Abraço,

T.
