### ISSUE TITLE
[chimera-admin] script not working

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#78]
`chimera-admin` script is not working. See below.

```
(chimera)dhcp-10-181-27-26:chimera-lna william$ chimera-admin -L
Traceback (most recent call last):
  File "/Users/william/.virtualenvs/chimera/bin/chimera-admin", line 313, in <module>
    d = doStuff(options, args)
  File "/Users/william/.virtualenvs/chimera/bin/chimera-admin", line 76, in __init__
    self.paths["instruments"].expand(cp.instruments)
AttributeError: 'list' object has no attribute 'expand'
```

**Comment by wschoenell** [comment]
Removed
